### PR TITLE
RFE: introduce a Makefile and .gitignore

### PR DESCRIPTION
**Pull request by thorduri**
Addresses #1 and adds some documentation to the README.

Is there any interest in minimal CI integration, e.g. travis ?
If so, I can submit a PR for that (some org work required by repository owners tho).

Signed-off-by: Thordur Bjornsson <thorduri@secnorth.net>

### CODE REVIEW

**Comment by mheon** [comment]
Thanks for your work - makefile definitely looks useful.

On testing: At some point last year, I was looking into porting the main libseccomp test suite to Go, as it's a lot more comprehensive than the existing test suite. I haven't had time to actually implement this, and I don't think it's worth setting up Travis until we have the full test suite in place (the existing tests aren't particularly extensive).

**Comment by thorduri** [comment]
> Thanks for your work - makefile definitely looks useful.

No problem.

> On testing: At some point last year, I was looking into porting the main libseccomp test suite to Go, as it's a lot more comprehensive than the existing test suite. I haven't had time to actually implement this, and I don't think it's worth setting up Travis until we have the full test suite in place (the existing tests aren't particularly extensive).

This would "fix" https://github.com/seccomp/libseccomp-golang/pull/13 ? 

I've already started down this path (adding an `examples/` directory, and porting the [libseccomp](https://github.com/seccomp/libseccomp/tree/master/tests) over as applicable, basing my work on https://github.com/seccomp/libseccomp-golang/pull/13.

It would be in my opinion worth it, to get that PR merged, some tests ported over, travis added and then start flailing at the rest of them.

**Comment by mheon** [comment]
That sounds like a good solution - the self-test routines do exercise all of the API by design, so they act as good examples as well.

**Comment by pcmoore** [comment]
Thanks, at a quick glance this looks really good!  I'll give this a closer review later and merge if everything is okay.

**Comment by pcmoore** [comment]
Merged via 1cb26b62139acaab9b64c5f91f84a4dc491e7974 and 206feef4a24ce01a8773f6aa37e92922172de726, thank you.

**Pull request closed without merging**
