### PR TITLE
RFE: refactor the Errno(-1 * retCode) pattern

### PR DESCRIPTION
**Pull request by nodakai**
(Based on PR #27)

Replace the common pattern `sycall.Errno(-1 * retCode)` with a new utility `errRc()`

### CODE REVIEW

**Comment by pcmoore** [comment]
Seems reasonable to me, but I'm not the golang expert here; @mheon?

**Comment by mheon** [comment]
Agree, change seems fine. LGTM.

**Comment by pcmoore** [comment]
Cool, go ahead and merge it then 😉

**Comment by mheon** [comment]
Little late in the day, I'll hit it tomorrow morning

**Comment by pcmoore** [comment]
No problem, just wanted to remind you that you're the main maintainer of this code base, if it looks good to everyone go ahead and merge it :)

**Comment by mheon** [comment]
Committed to master as bebea070d2b1ac181c7fedd289305a8fb68e3ddf

**Pull request closed without merging**
