### PR TITLE
BUG: add SECURITY.md

### PR DESCRIPTION
**Pull request by kolyshkin**
Fixes: #83

### CODE REVIEW

**Comment by pcmoore** [comment]
Thanks @kolyshkin, would you mind adding your sign-off to the patch?

**Comment by pcmoore** [comment]
@drakenclimber I assume you're okay with this given that it just refers to the main project's security policy?

**Review by pcmoore — CHANGES_REQUESTED** [review]
Needs a sign-off, but otherwise it looks good to me.

**Review by drakenclimber — APPROVED** [review]
Looks good to me.  Thanks @kolyshkin

`Acked-by: Tom Hromatka <tom.hromatka@oracle.com>`

**Review by pcmoore — APPROVED** [review]

**Comment by pcmoore** [comment]
Merged via 2a71848205430267e34457b3b771a37e7d584956, thanks!

**Pull request closed without merging**
