### PR TITLE
BUG: expose option ActKillProcess

### PR DESCRIPTION
**Pull request by pjbgf**
Added the ActKillProcess option. 
I noticed that in the documentation we were stating that ActKill was killing the process. My understanding is that it wasn't the case, so I ended up also adding ActKillThread to improve clarity.

The ActKill still exists and does the same as ActKillThread, which is the same as in the C implementation and in the man page documentation.

I wasn't really sure what would be the best way to test the two new filters, so I only tested the filter creation with those values. Any feedback is greatly appreciated.

### CODE REVIEW

**Comment by pcmoore** [comment]
This seems like a bugfix to me, what do you say @mheon?

**Comment by mheon** [comment]
It is technically expanding the public-facing API so it may be worth a version bump, but overall, changes seem simple enough. Code LGTM, will test tomorrow and see about merging if that looks good.

**Comment by pjbgf** [comment]
@mheon please let me know of any changes you need me to make.

**Comment by pjbgf** [comment]
@pcmoore @mheon Is there anything I can do to help getting this PR over the line?

**Comment by pcmoore** [comment]
I'm sorry for the delay @pjbgf.

@mheon can you weigh in on this please?  Also, if you are no longer able to maintain this project, please let me know so I can make other arrangements.

**Comment by mheon** [comment]
Sorry about the delay here, testing now.

@pcmoore I'm still happy to contribute when I can, but the day job is taking more and more of my time - finding someone to take the lead here might be a good idea.

**Comment by mheon** [comment]
Pushed to master as 24f29379854785de68bbd44630cc093b22b4dc29 - closing

**Comment by pcmoore** [comment]
@mheon okay, I'll see what I can do.

**Comment by thaJeztah** [comment]
Are there plans to tag a new release with these changes? (arrived here after checking if our dependencies were up-to-date, and noticed some commits were merged to master after the last release)

**Comment by pcmoore** [comment]
Hi @thaJeztah.  No, there are no real plans for a new release, but some of that is simply because we are without someone to really "drive the ship" for the libseccomp golang bindings.

At this point I think @drakenclimber and I need to start maintaining the golang bindings as well as the main libseccomp project.  Give us some time to get things sorted out and we can can a new release.

**Comment by thaJeztah** [comment]
Gotcha, thanks! Let me also look around if there's people that have the knowledge to assist if possible 👍

**Comment by gsauthof** [comment]
FWIW, with version 0.9.1 and just `seccomp.ActKill` the experience for my program is as if I specify `seccomp.ActLog`, i.e. the syscall violations are just logged. The program doesn't panic, continues and finishes successfully.

(I tested this by not whitelisting `nanosleep` and `mprotect` with are always called by the Go runtime when I run my program.)

When updating to the current libseccomp-golang master I can compile with `seccomp.ActKillProcess` and the program is reliably killed on the first violation.

Since this is the most useful behavior for my use case I would appreciate a new release that includes the `ActKillProcess` action.

**Comment by pjbgf** [comment]
@pcmoore @thaJeztah would it make sense to re-open this PR until a new release is planned?

**Pull request closed without merging**
