### PR TITLE
RFE: misc nits 

### PR DESCRIPTION
**Pull request by kolyshkin**
These are the collection of small source code cleanups and nits. No functional change. See individual commits for details.

### CODE REVIEW

**Review by pcmoore — APPROVED** [review]
Looks good to me.
```
Acked-by: Paul Moore <paul@paul-moore.com>
```

**Comment by kolyshkin** [comment]
First commit removed (will be part of #70 instead), so this becomes even more trivial to review.

@drakenclimber PTAL

**Review by drakenclimber — APPROVED** [review]
Looks good to me.  I'll merge it in a bit.

`Acked-by: Tom Hromatka <tom.hromatka@oracle.com>`

**Comment by drakenclimber** [comment]
Merged via commits 5fb274613cf7c836094e52efa7e4ab536f6f7608, 5444a06899d136f2f54fe2b3e9ce1228362fc04a, and 0bfc29aba0012bc99865104bc485f3446c76d48c.  Thanks all!

**Comment by drakenclimber** [comment]
One question, @kolyshkin - I'm looking through the Github Actions log right now.  Where does Github Actions run the gofumpt linter?  I don't see it in any of the logs

**Comment by kolyshkin** [comment]
> One question, @kolyshkin - I'm looking through the Github Actions log right now. Where does Github Actions run the gofumpt linter? I don't see it in any of the logs.

It's part of golangci-lint run, which does not print the names of enabled linters (unless those report issues).

So what you can see in the logs is 

>  Running [/home/runner/golangci-lint-1.41.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
>  golangci-lint found no issues
>  Ran golangci-lint in 7986ms

It's similar locally:
```console
kir@kd:~/go/src/github.com/seccomp/libseccomp-golang$ make lint
golangci-lint run .
kir@kd:~/go/src/github.com/seccomp/libseccomp-golang$
```

Although you can see which linters are enabled by running `golangci-lint linters`:
```
$ golangci-lint linters
Enabled by your configuration linters:
deadcode: Finds unused code [fast: false, auto-fix: false]
errcheck: Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases [fast: false, auto-fix: false]
gofumpt: Gofumpt checks whether code was gofumpt-ed. [fast: true, auto-fix: true]
gosimple (megacheck): Linter for Go source code that specializes in simplifying a code [fast: false, auto-fix: false]
.....
```

Now, golangci-lint would error out if a linter is specified which can't be run:
```console
kir@kd:~/go/src/github.com/seccomp/libseccomp-golang$ cat .golangci.yml 
# For documentation, see https://golangci-lint.run/usage/configuration/
linters:
  enable:
    - gofumpt
kir@kd:~/go/src/github.com/seccomp/libseccomp-golang$ sed -i 's/gofumpt/gofoo/' .golangci.yml 
kir@kd:~/go/src/github.com/seccomp/libseccomp-golang$ golangci-lint run .
ERRO Running error: unknown linters: 'gofoo', run 'golangci-lint help linters' to see the list of supported linters 
kir@kd:~/go/src/github.com/seccomp/libseccomp-golang$ 
```

Ultimately, though, if you need to be 100% sure, open a test DNM/draft PR with a deliberately introduced issue which gofumpt is supposed to fix.

**Pull request closed without merging**
